"""Projection adapters — one spec, many destinations.

The ``requirements.yaml`` produced by the architect is the source of truth. These
adapters *project* it into the file each downstream tool expects, so the same
behavioral contract reaches every coding agent / SDD framework:

- ``agents-md``  → ``AGENTS.md``           (universal coding-agent constitution)
- ``claude``     → ``CLAUDE.md``           (Claude Code)
- ``cursor``     → ``.cursor/rules/*.mdc`` (Cursor)
- ``spec-kit``   → ``spec.md``             (GitHub Spec Kit narrative)
- ``kiro``       → ``requirements.md``     (AWS Kiro, EARS syntax)

These are deterministic text renderers — no LLM, no enforcement.
"""

from __future__ import annotations

from typing import Any

TARGETS = ("agents-md", "claude", "cursor", "spec-kit", "kiro", "adr")
_PRODUCT_TARGETS = ("spec-kit", "kiro")


def project(doc: dict[str, Any], to: str) -> str:
    """Render ``doc`` into the file format for target ``to``."""
    to = to.lower()
    spec_type = (doc.get("meta", {}) or {}).get("spec_type")

    if to in ("adr", "architecture"):
        return _adr_md(doc)
    if spec_type == "technical_requirements" and to in ("spec-kit", "speckit", "spec", "kiro", "ears"):
        raise ValueError(
            f"Target {to!r} expects a product spec. For a technical spec use 'adr' "
            "(or 'agents-md' / 'claude' / 'cursor')."
        )
    if to in ("agents-md", "agents", "agentsmd"):
        return _agents_md_technical(doc) if spec_type == "technical_requirements" else _agents_md(doc)
    if to in ("claude", "claude-code", "claudemd"):
        return _claude_md(doc)
    if to in ("cursor", "cursor-rules", "mdc"):
        return _cursor_mdc(doc)
    if to in ("spec-kit", "speckit", "spec"):
        return _spec_md(doc)
    if to in ("kiro", "ears"):
        return _kiro_md(doc)
    raise ValueError(f"Unknown projection target {to!r}. Choose one of: {', '.join(TARGETS)}")


def _name(doc: dict[str, Any]) -> str:
    return (doc.get("meta", {}) or {}).get("system_name", "agent")


def _forbidden(doc: dict[str, Any]) -> list[str]:
    out = []
    for a in doc.get("actions", []) or []:
        if a.get("policy") == "forbidden":
            tools = a.get("tools") or [a.get("tool", "?")]
            out.extend(str(t) for t in tools)
    return out


def _approval_required(doc: dict[str, Any]) -> list[str]:
    out = []
    for a in doc.get("actions", []) or []:
        if a.get("policy") == "approve":
            out.append(str(a.get("tool") or a.get("tools") or a.get("id")))
    return out


def _never_rules(doc: dict[str, Any]) -> list[str]:
    return [p.get("requirement", p.get("incident", "")) for p in doc.get("safety", []) or []]


def _rules_block(doc: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    forbidden = _forbidden(doc)
    if forbidden:
        lines.append(f"- NEVER call these tools (forbidden): {', '.join(forbidden)}.")
    for action in _approval_required(doc):
        lines.append(f"- Require human approval before: {action}.")
    for rule in _never_rules(doc):
        if rule:
            lines.append(f"- Safety: {rule}")
    for t in (doc.get("tasks", {}) or {}).values():
        if t.get("no_draft"):
            lines.append("- For out-of-scope requests: produce NO draft; route to a human immediately.")
            break
    return lines


def _agents_md(doc: dict[str, Any]) -> str:
    name = _name(doc)
    meta = doc.get("meta", {}) or {}
    out = [
        f"# AGENTS.md — {name}",
        "",
        "> Generated by mycontext requirements-architect from `requirements.yaml`.",
        "> `requirements.yaml` is the source of truth; regenerate this file when it changes.",
        "",
        "## Intent",
        "",
        meta.get("intent", ""),
        "",
        "## Operating rules (the constitution)",
        "",
    ]
    out += _rules_block(doc) or ["- (no hard rules derived yet — review requirements.yaml)"]
    out += [
        "",
        "## Definition of done (release gates)",
        "",
    ]
    for g in (doc.get("gates", {}) or {}).get("items", []):
        out.append(f"- `{g.get('scope')}`: {g.get('metric')} {('>= ' + str(g.get('threshold'))) if isinstance(g.get('threshold'), (int, float)) else g.get('threshold')}"
                   + ("  (hard gate)" if g.get("hard_gate") else ""))
    out += [
        "",
        "## Open questions (resolve before trusting this spec)",
        "",
    ]
    for q in doc.get("open_questions", []) or []:
        flag = "**(blocking)** " if q.get("blocking") else ""
        out.append(f"- {flag}`{q.get('id')}` — {q.get('question')} (affects `{q.get('affects')}`)")
    out.append("")
    return "\n".join(out)


def _claude_md(doc: dict[str, Any]) -> str:
    name = _name(doc)
    out = [
        f"# CLAUDE.md — {name}",
        "",
        "The behavioral contract lives in `requirements.yaml` (source of truth).",
        "Read it before changing behavior; keep these rules invariant:",
        "",
    ]
    out += _rules_block(doc) or ["- (review requirements.yaml)"]
    out += [
        "",
        "When in doubt, prefer refusing / escalating over guessing. Every production",
        "miss becomes a new eval case in `datasets/` within the same fix PR.",
        "",
    ]
    return "\n".join(out)


def _cursor_mdc(doc: dict[str, Any]) -> str:
    name = _name(doc)
    rules = _rules_block(doc) or ["- (review requirements.yaml)"]
    body = "\n".join(rules)
    return (
        "---\n"
        f"description: Behavioral contract for {name} (from requirements.yaml)\n"
        "alwaysApply: true\n"
        "---\n\n"
        f"# {name} — operating rules\n\n"
        "Source of truth: `requirements.yaml` (generated by mycontext requirements-architect).\n"
        "Regenerate this rule when the spec changes.\n\n"
        "## Invariants\n\n"
        f"{body}\n"
    )


def _spec_md(doc: dict[str, Any]) -> str:
    name = _name(doc)
    meta = doc.get("meta", {}) or {}
    out = [
        f"# Specification — {name}",
        "",
        f"Status: {meta.get('status', 'draft')} · Spec version: {meta.get('spec_version', '0.1.0')}",
        "",
        "## Overview",
        "",
        meta.get("intent", ""),
        "",
        "## User scenarios (tasks)",
        "",
    ]
    rubrics = doc.get("rubrics", {}) or {}
    for tid, t in (doc.get("tasks", {}) or {}).items():
        out.append(f"### {tid} — {t.get('name')}")
        if t.get("example"):
            out.append(f"- Example: {t.get('example')}")
        out.append(f"- Risk: {t.get('risk')} · Handling: {t.get('handling')}")
        rid = t.get("rubric")
        rub = rubrics.get(rid, {})
        crit = rub.get("criteria", []) if isinstance(rub, dict) else []
        if crit:
            out.append("- Acceptance criteria:")
            for c in crit:
                out.append(f"  - {c.get('text')} (`{c.get('grader')}`)")
        out.append("")
    out += ["## Non-negotiable constraints", ""]
    out += [f"- {r}" for r in _rules_block(doc)]
    out += ["", "## Open questions", ""]
    for q in doc.get("open_questions", []) or []:
        out.append(f"- `{q.get('id')}` {q.get('question')}")
    out.append("")
    return "\n".join(out)


def _adr_md(doc: dict[str, Any]) -> str:
    """Architecture/technical summary for a technical-requirements spec."""
    name = _name(doc)
    arch = doc.get("architecture", {}) or {}
    out = [
        f"# Technical Architecture — {name}",
        "",
        "> Generated by mycontext from the technical-requirements spec.",
        "> Source of truth: `technical-requirements.yaml`.",
        "",
        "## Architecture",
        "",
        f"- Pattern: {arch.get('pattern', 'TODO')}",
        f"- Orchestration: {(arch.get('orchestration') or {}).get('loop', 'TODO')}",
        f"- State: short-term={(arch.get('state') or {}).get('short_term', 'TODO')}; "
        f"long-term={(arch.get('state') or {}).get('long_term', 'TODO')}",
        "",
        "## Guardrails",
        "",
    ]
    guardrails = doc.get("guardrails", {}) or {}
    for layer in ("input", "processing", "output"):
        for item in guardrails.get(layer, []) or []:
            serves = ", ".join(item.get("serves", [])) or "—"
            out.append(f"- ({layer}) {item.get('control')}  ·  serves: {serves}")
    out += ["", "## Forbidden tools", ""]
    for f in (doc.get("tools", {}) or {}).get("forbidden", []) or []:
        out.append(f"- {', '.join(str(t) for t in f.get('tools', []))}  ·  serves: {', '.join(f.get('serves', [])) or '—'}")
    out += ["", "## Security (OWASP Agentic)", ""]
    for o in (doc.get("security", {}) or {}).get("owasp_agentic_top10", []) or []:
        out.append(f"- {o.get('risk')}: {o.get('mitigation')}  ·  serves: {', '.join(o.get('serves', [])) or '—'}")
    out += ["", "## Open questions", ""]
    for q in doc.get("open_questions", []) or []:
        out.append(f"- `{q.get('id')}` {q.get('question')}")
    out.append("")
    return "\n".join(out)


def _agents_md_technical(doc: dict[str, Any]) -> str:
    """A constitution slice derived from technical guardrails (for coding agents)."""
    name = _name(doc)
    out = [
        f"# AGENTS.md — {name} (technical)",
        "",
        "> Generated by mycontext from `technical-requirements.yaml`.",
        "",
        "## Engineering invariants",
        "",
    ]
    guardrails = doc.get("guardrails", {}) or {}
    for layer in ("input", "processing", "output"):
        for item in guardrails.get(layer, []) or []:
            out.append(f"- {item.get('control')}")
    for f in (doc.get("tools", {}) or {}).get("forbidden", []) or []:
        out.append(f"- NEVER implement/call: {', '.join(str(t) for t in f.get('tools', []))}.")
    out.append("")
    return "\n".join(out)


def _kiro_md(doc: dict[str, Any]) -> str:
    """EARS-style requirements (WHEN/THE SYSTEM SHALL)."""
    name = _name(doc)
    out = [f"# Requirements — {name} (EARS)", ""]
    n = 1
    for tid, t in (doc.get("tasks", {}) or {}).items():
        trigger = t.get("example") or t.get("name")
        if t.get("no_draft"):
            response = "produce no draft and route the request to a human immediately"
        else:
            response = f"handle it via '{t.get('handling')}' and satisfy rubric {t.get('rubric')}"
        out.append(f"{n}. WHEN {trigger}, THE SYSTEM SHALL {response}.")
        n += 1
    for a in doc.get("actions", []) or []:
        if a.get("policy") == "approve":
            tool = a.get("tool") or a.get("tools")
            out.append(f"{n}. WHEN about to {tool}, THE SYSTEM SHALL require human approval before proceeding.")
            n += 1
        elif a.get("policy") == "forbidden":
            tools = a.get("tools") or [a.get("tool")]
            out.append(f"{n}. THE SYSTEM SHALL NEVER {', '.join(str(x) for x in tools)}.")
            n += 1
    for p in doc.get("safety", []) or []:
        out.append(f"{n}. THE SYSTEM SHALL ENSURE: {p.get('requirement')}.")
        n += 1
    out.append("")
    return "\n".join(out)
